### ISSUE TITLE
建议发个npm包

### ISSUE THREAD

**Issue by anto1717** [mhbseal/html5ImgCompress#6]
非常有用的工具，期待能以npm包的形式供大家引用。

**Comment by shangga** [comment]
@liuanto 在webpack编译的项目中如何使用？

**Comment by liuanto** [comment]
@shangga 可以直接引用dist目录下打包好的js。但是不够优雅，最好的方式还是希望作者发布一个npm包，允许通过CommonJS规范的方式引用。
